// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtqdplgznbSAfl0YlNDa-88fnat_Wv4tI',
    appId: '1:691879653200:android:2fd41462d3144415420655',
    messagingSenderId: '691879653200',
    projectId: 'rockpaperscissor-4c7a8',
    storageBucket: 'rockpaperscissor-4c7a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcUtbKwk_n8JcGKqoE_m9m5_ho0R4Yvo',
    appId: '1:691879653200:ios:fb71edcfa4cc0987420655',
    messagingSenderId: '691879653200',
    projectId: 'rockpaperscissor-4c7a8',
    storageBucket: 'rockpaperscissor-4c7a8.appspot.com',
    androidClientId: '691879653200-fabldtip1h3meak5a08v7n9kr1nhhf1g.apps.googleusercontent.com',
    iosClientId: '691879653200-1p36pcqt4llcllj1jrleoopprps5g7eo.apps.googleusercontent.com',
    iosBundleId: 'com.rockpaperscissor.rockpaperscissor',
  );
}
